# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: af2b67c46244479c09ea0a538e8548f865070b27fc5a8a53633566708bad92c3cf446106cedbb52f3f8873bbc59e150b1e69e19a0c877a059a24fb7baa388c03

test:
  secret_key_base: 02b20ecfe3aef1f8549e1cd167bbe8bfa7c0496ecb4ac16c1d333ad030cc9e7b71ef1011c3358e7a1eefba189513c38edc3fdac0629bc42f428b83891fc1c4c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
